packages:
  - .
allowBuilds:
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  "@prisma/client": set this to true or false
  "@prisma/engines": set this to true or false
  prisma: set this to true or false
  esbuild: set this to true or false
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - "@prisma/client"
  - "@prisma/engines"
  - prisma
  - esbuild
