import type { CharacterConfig, CharacterSlug } from "@/types";

export const CHARACTERS: CharacterConfig[] = [
  {
    id: "01",
    slug: "fat-pig",
    displayName: "Fat Pig",
    vibe: "stretched shirt, coffee, tired",
    primary: "#F5A9B8",
    secondary: "#7A3D4D",
    bodyShape: "round",
    has3DModel: true,
  },
  {
    id: "02",
    slug: "dirty-donkey",
    displayName: "Dirty Donkey",
    vibe: "messy fur, crooked badge",
    primary: "#A89B86",
    secondary: "#3D3528",
    bodyShape: "tall",
    has3DModel: true,
  },
  {
    id: "03",
    slug: "cockroach",
    displayName: "Cockroach",
    vibe: "oversized headphones, tiny chair",
    primary: "#5C3A1E",
    secondary: "#1F1408",
    bodyShape: "flat",
    has3DModel: true,
  },
  {
    id: "04",
    slug: "kechua",
    displayName: "Kechua",
    vibe: "long worm, tie, expressive eyes",
    primary: "#C49A6C",
    secondary: "#5C3A1E",
    bodyShape: "worm",
    has3DModel: true,
  },
  {
    id: "05",
    slug: "office-rat",
    displayName: "Office Rat",
    vibe: "hoodie, coffee, suspicious",
    primary: "#8A8A95",
    secondary: "#2A2A30",
    bodyShape: "tiny",
    has3DModel: false,
  },
  {
    id: "06",
    slug: "machhar",
    displayName: "Machhar",
    vibe: "tiny, buzzing, annoying",
    primary: "#3D3D45",
    secondary: "#1A1A20",
    bodyShape: "tiny",
    has3DModel: false,
  },
  {
    id: "07",
    slug: "corporate-bhains",
    displayName: "Corporate Bhains",
    vibe: "slow, formal, horns",
    primary: "#6B6B70",
    secondary: "#2A2A30",
    bodyShape: "tall",
    has3DModel: false,
  },
  {
    id: "08",
    slug: "chipkali",
    displayName: "Chipkali",
    vibe: "wall climber, beady eyes",
    primary: "#7BA05B",
    secondary: "#2E3D22",
    bodyShape: "flat",
    has3DModel: false,
  },
  {
    id: "09",
    slug: "ganda-mendak",
    displayName: "Ganda Mendak",
    vibe: "wet, slimy, unbothered",
    primary: "#7BA86B",
    secondary: "#2E4D22",
    bodyShape: "round",
    has3DModel: false,
  },
  {
    id: "10",
    slug: "besharam-bandar",
    displayName: "Besharam Bandar",
    vibe: "loud, banana in hand",
    primary: "#8B5A3C",
    secondary: "#3D2418",
    bodyShape: "round",
    has3DModel: false,
  },
  {
    id: "11",
    slug: "sewer-pigeon",
    displayName: "Sewer Pigeon",
    vibe: "droopy eye, knows too much",
    primary: "#9B9B9F",
    secondary: "#3A3A40",
    bodyShape: "round",
    has3DModel: false,
  },
  {
    id: "12",
    slug: "dustbin-panda",
    displayName: "Dustbin Panda",
    vibe: "rummages, sleepy",
    primary: "#E8E8EC",
    secondary: "#3A3A40",
    bodyShape: "round",
    has3DModel: false,
  },
  {
    id: "13",
    slug: "sleepy-buffalo",
    displayName: "Sleepy Buffalo",
    vibe: "horns, half asleep",
    primary: "#6B5240",
    secondary: "#2A1F18",
    bodyShape: "tall",
    has3DModel: false,
  },
  {
    id: "14",
    slug: "toxic-frog",
    displayName: "Toxic Frog",
    vibe: "neon, smug",
    primary: "#A8E85C",
    secondary: "#3D5C1E",
    bodyShape: "round",
    has3DModel: false,
  },
  {
    id: "15",
    slug: "greasy-monkey",
    displayName: "Greasy Monkey",
    vibe: "oily, jittery",
    primary: "#8B6F4F",
    secondary: "#3D2E1E",
    bodyShape: "round",
    has3DModel: false,
  },
  {
    id: "16",
    slug: "broken-lizard",
    displayName: "Broken Lizard",
    vibe: "one eye, tail bent",
    primary: "#7BA86B",
    secondary: "#2E4D22",
    bodyShape: "long",
    has3DModel: false,
  },
  {
    id: "17",
    slug: "stupid-goat",
    displayName: "Stupid Goat",
    vibe: "chewing, vacant stare",
    primary: "#D8D2C8",
    secondary: "#5C5648",
    bodyShape: "tall",
    has3DModel: false,
  },
  {
    id: "18",
    slug: "basement-rat",
    displayName: "Basement Rat",
    vibe: "red eyes, glowing",
    primary: "#9B5C5C",
    secondary: "#3D1F1F",
    bodyShape: "tiny",
    has3DModel: false,
  },
];

export const CHARACTER_BY_SLUG: Record<CharacterSlug, CharacterConfig> =
  Object.fromEntries(CHARACTERS.map((c) => [c.slug, c])) as Record<
    CharacterSlug,
    CharacterConfig
  >;

export function getCharacter(slug: CharacterSlug): CharacterConfig {
  return CHARACTER_BY_SLUG[slug];
}
